version: '2'
services:
  app:
    command: "npm start"
    restart: always
    environment:
     - NODE_ENV=production
    ports:
     - "3000:3000"
  dns:
    command: "npm run dns-server"
    restart: always
    environment:
     - NODE_ENV=production
  db:
    restart: always
